In [2]:
#### 1. What is a Python library? Why do we use Python libraries?

"""
a. A Python library is a collection of pre-written code that provides various functionalities and utilities for Python programming. 
b. Libraries are created to make it easier for developers to perform common tasks without having to write code from scratch. 
c. They include functions, classes, and modules that can be reused.

We use Python libraries to:
- Save time by avoiding repetitive coding.
- Leverage well-tested and optimized functions for complex tasks.
- Enhance code readability and maintainability.
"""

'\na. A Python library is a collection of pre-written code that provides various functionalities and utilities for Python programming. \nb. Libraries are created to make it easier for developers to perform common tasks without having to write code from scratch. \nc. They include functions, classes, and modules that can be reused.\n\nWe use Python libraries to:\n- Save time by avoiding repetitive coding.\n- Leverage well-tested and optimized functions for complex tasks.\n- Enhance code readability and maintainability.\n'

In [3]:
#### 2. What is the difference between Numpy array and List?

"""
Numpy Array:
a. Provides more efficient storage and data manipulation.
b. Supports a wide range of mathematical operations and functions.
c. Requires the numpy library.
d. Homogeneous: All elements must be of the same data type.

List:
a. Built into Python, no additional libraries required.
b. More flexible: Can contain mixed data types.
c. Less efficient for large numerical operations compared to Numpy arrays.
"""

'\nNumpy Array:\na. Provides more efficient storage and data manipulation.\nb. Supports a wide range of mathematical operations and functions.\nc. Requires the numpy library.\nd. Homogeneous: All elements must be of the same data type.\n\nList:\na. Built into Python, no additional libraries required.\nb. More flexible: Can contain mixed data types.\nc. Less efficient for large numerical operations compared to Numpy arrays.\n'

In [4]:
"""
3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
"""

import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print("Shape:", arr.shape)      
print("Size:", arr.size)        
print("Dimension:", arr.ndim)   

Shape: (3, 4)
Size: 12
Dimension: 2


In [5]:
"""
4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
"""

import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

first_row = arr[0]
print("First row:", first_row)

First row: [1 2 3 4]


In [6]:
"""
5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
"""

import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

element = arr[2, 3]
print("Element at third row, fourth column:", element)

Element at third row, fourth column: 12


In [7]:
"""
6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
"""

import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

odd_indexed_elements = arr[:, 1::2]
print("Odd-indexed elements:", odd_indexed_elements)

Odd-indexed elements: [[ 2  4]
 [ 6  8]
 [10 12]]


In [8]:
### 7. How can you generate a random 3x3 matrix with values between 0 and 1?

import numpy as np

random_matrix = np.random.rand(3, 3)
print("Random 3x3 matrix with values between 0 and 1:\n", random_matrix)

Random 3x3 matrix with values between 0 and 1:
 [[0.46365954 0.40476638 0.36186964]
 [0.18213671 0.12682595 0.77763064]
 [0.26164474 0.97491344 0.3509065 ]]


In [9]:
### 8. Describe the difference between np.random.rand and np.random.randn?

"""
- np.random.rand: Generates random numbers from a uniform distribution over [0, 1).

- np.random.randn: Generates random numbers from a standard normal distribution with mean 0 and variance 1.
"""

'\n- np.random.rand: Generates random numbers from a uniform distribution over [0, 1).\n\n- np.random.randn: Generates random numbers from a standard normal distribution with mean 0 and variance 1.\n'

In [10]:
""" 
9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
"""

import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Increase the dimension by adding an extra dimension
increased_dim = np.expand_dims(arr, axis=0)
print("Array with increased dimension:\n", increased_dim)

Array with increased dimension:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [11]:
"""
10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
"""

import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

transposed_arr = arr.T
print("Transposed array:\n", transposed_arr)

Transposed array:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [12]:
"""
11. Consider the following matrix:
Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python:
1. Index wise multiplication
2. Matrix multiplication
3. Add both the matrics
4. Subtract matrix B from A
5. Divide Matrix B by A
"""

import numpy as np

# Define matrices A and B
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

B = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# 1. Index wise multiplication
index_wise_multiplication = A * B
print("Index wise multiplication:\n", index_wise_multiplication)

# 2. Matrix multiplication
# Matrix multiplication is performed using dot product (or @ operator for simplicity)
matrix_multiplication = np.dot(A, B.T)  # B.T is the transpose of B for proper multiplication
print("Matrix multiplication:\n", matrix_multiplication)

# 3. Add both matrices
addition = A + B
print("Addition:\n", addition)

# 4. Subtract matrix B from A
subtraction = A - B
print("Subtraction:\n", subtraction)

# 5. Divide Matrix B by A (element-wise division)
# To avoid division by zero errors, make sure no elements in A are zero
division = B / A
print("Element-wise division:\n", division)

Index wise multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Matrix multiplication:
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
Addition:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Subtraction:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Element-wise division:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
#### 12.  Which function in Numpy can be used to swap the byte order of an array?

"""
np.byteswap: 
    - Swaps the byte order of the elements in an array.
"""

'\nnp.byteswap: \n    - Swaps the byte order of the elements in an array.\n'

In [16]:
#### 13.  What is the significance of the np.linalg.inv function?

"""
np.linalg.inv: 
    - Computes the inverse of a matrix. 
    - The inverse of a matrix A is a matrix B such that A * B = I, where I is the identity matrix.
"""

'\nnp.linalg.inv: \n    - Computes the inverse of a matrix. \n    - The inverse of a matrix A is a matrix B such that A * B = I, where I is the identity matrix.\n'

In [18]:
#### 14. What does the np.reshape function do, and how is it used?

"""
np.reshape: 
    - Changes the shape of an array without changing its data. 
    - You specify the new shape as a tuple.
"""

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = np.reshape(arr, (2, 3))
print("Reshaped array:\n", reshaped_arr)

Reshaped array:
 [[1 2 3]
 [4 5 6]]


In [19]:
#### 15. What is broadcasting in Numpy?

"""
Broadcasting: 
    - Allows numpy to perform operations on arrays of different shapes by automatically expanding the smaller array to match the shape of the larger array. 
    - This makes operations more efficient and simpler.
"""

#### Example: adding a scalar to an array is an example of broadcasting where the scalar is broadcasted across all elements of the array.

import numpy as np

arr = np.array([1, 2, 3])
result = arr + 5  # Broadcasting: 5 is added to each element of the array
print("Broadcasted result:", result)

Broadcasted result: [6 7 8]
