In [1]:
import numpy as np

In [2]:
# Define the sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [3]:
# Initialize network parameters
input_size = 3  # Number of input features
hidden_size = 4  # Number of neurons in the hidden layer
output_size = 1  # Number of output neurons

# Randomly initialize weights and biases
np.random.seed(42)
W1 = np.random.randn(input_size, hidden_size)
b1 = np.random.randn(hidden_size)
W2 = np.random.randn(hidden_size, output_size)
b2 = np.random.randn(output_size)

In [4]:
# Print the initial weights and biases for reference
print("Initial weights and biases:")
print("W1:\n", W1)
print("b1:\n", b1)
print("W2:\n", W2)
print("b2:\n", b2)

Initial weights and biases:
W1:
 [[ 0.49671415 -0.1382643   0.64768854  1.52302986]
 [-0.23415337 -0.23413696  1.57921282  0.76743473]
 [-0.46947439  0.54256004 -0.46341769 -0.46572975]]
b1:
 [ 0.24196227 -1.91328024 -1.72491783 -0.56228753]
W2:
 [[-1.01283112]
 [ 0.31424733]
 [-0.90802408]
 [-1.4123037 ]]
b2:
 [1.46564877]


In [5]:
# Define the forward propagation function
def forward_propagation(X):
    # Input to hidden layer
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    
    # Hidden layer to output layer
    z2 = np.dot(a1, W2) + b2
    output = sigmoid(z2)
    
    return output

In [6]:
# Example input
X = np.array([[0.1, 0.2, 0.3],
              [0.4, 0.5, 0.6]])

In [7]:
# Perform forward propagation
output = forward_propagation(X)
print("\nOutput of the neural network:")
print(output)


Output of the neural network:
[[0.55998689]
 [0.49571601]]
